
export const habilidades = [
  "Se desloca para frente",
  "Se desloca para trás",
  "Gira no lugar",
  "Gira enquanto se desloca para frente",
  "Gira enquanto se desloca para trás",
  "Manobra lateralmente",
  "Alcança objetos",
  "Altera posicionamento corporal",
  "Transfere peso",
  "Realiza transferências em nível",
  "Passa por porta com dobradiça",
  "Dobra e desdobra a cadeira de rodas",
  "Realiza transferências para o chão",
  "Sobe inclinação leve",
  "Desce inclinação leve",
  "Sobe inclinação íngreme",
  "Desce inclinação íngreme",
  "Rola em superfície macia",
  "Supera obstáculo",
  "Sobe meio-fio baixo",
  "Desce meio-fio baixo",
  "Sobe meio-fio alto",
  "Desce meio-fio alto",
  "Realiza empinar estacionário",
  "Gira no lugar empinado",
  "Se desloca para frente/para trás empinado",
  "Desce meio-fio alto empinado",
  "Desce inclinação íngreme empinado",
  "Sobe escadas",
  "Desce escadas",
];

export const notas = ["0", "1", "2", "3", "NP", "TE"];